# Based on
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: unittest-linux.yaml

on: [push]

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

jobs:
  unittest-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        senzingapi-version: [staging]
    name: Python ${{ matrix.python-version }} using Senzing API ${{ matrix.senzingapi-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Senzing API
        uses: Senzing/github-action-install-senzing-api@latest
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}
      - name: Copy /etc files
        run: sudo cp testdata/senzing-license/g2.lic /etc/opt/senzing
      - name: Copy test database files
        run: mkdir /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db
      - name: Run python unittest
        run: python3 -m unittest tests/*.py
